### ISSUE TITLE
 Unsupported operator "Resize"

### ISSUE THREAD

**Issue by GreatV** [InfiniTensor/InfiniTensor#186]
```sh
python examples/python/onnx_inference.py pplite-seg.onnx
```

```
import backend: <module 'backend' from '/home/greatx/repos/InfiniTensor/pyinfinitensor/src/pyinfinitensor/backend.cpython-310-x86_64-linux-gnu.so'>
Traceback (most recent call last):
  File "/home/greatx/repos/InfiniTensor/examples/python/onnx_inference.py", line 24, in <module>
    model = OnnxStub(onnx_model, backend.cuda_runtime())
  File "/home/greatx/repos/InfiniTensor/pyinfinitensor/src/pyinfinitensor/onnx.py", line 806, in __init__
    raise Exception('Unsupported operator "{}"'.format(node.op_type))
Exception: Unsupported operator "Resize"
```

```
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃                    ┃ Original Model ┃ Simplified Model ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Add                │ 5              │ 5                │
│ ArgMax             │ 1              │ 1                │
│ AveragePool        │ 5              │ 5                │
│ BatchNormalization │ 46             │ 0                │
│ Cast               │ 13             │ 1                │
│ Concat             │ 16             │ 9                │
│ Constant           │ 293            │ 99               │
│ Conv               │ 47             │ 47               │
│ GlobalAveragePool  │ 1              │ 1                │
│ Mul                │ 6              │ 6                │
│ ReduceMax          │ 6              │ 6                │
│ ReduceMean         │ 6              │ 6                │
│ Relu               │ 40             │ 40               │
│ Resize             │ 7              │ 7                │
│ Shape              │ 12             │ 0                │
│ Sigmoid            │ 3              │ 3                │
│ Slice              │ 12             │ 0                │
│ Sub                │ 3              │ 3                │
│ Model Size         │ 30.7MiB        │ 30.6MiB          │
└────────────────────┴────────────────┴──────────────────┘
```

**Comment by whjthu** [comment]
您好，我们目前后端算子库做了 resize 算子，但前端忘了做 onnx 层的对接，之前算子覆盖性的测试没有做完全。这两天我们会补上

**Comment by kilinchange** [comment]
您好，前端已经补充了对 resize 算子的对接 #194 ，这两天会合入到 master 中

**Comment by whjthu** [comment]
#194 merged
