### ISSUE TITLE
onnx_inference.py can't work with yolov8n.onnx

### ISSUE THREAD

**Issue by GreatV** [InfiniTensor/InfiniTensor#187]
It gets stuck during processing.

```
❯ python examples/python/onnx_inference.py yolov8n.onnx 
import backend: <module 'backend' from '/home/greatx/repos/InfiniTensor/pyinfinitensor/src/pyinfinitensor/backend.cpython-310-x86_64-linux-gnu.so'>
^CTraceback (most recent call last):
  File "/home/greatx/repos/InfiniTensor/examples/python/onnx_inference.py", line 24, in <module>
    model = OnnxStub(onnx_model, backend.cuda_runtime())
  File "/home/greatx/repos/InfiniTensor/pyinfinitensor/src/pyinfinitensor/onnx.py", line 93, in __init__
    continue
KeyboardInterrupt

```
took 4m11s

**Comment by whjthu** [comment]
麻烦请提供一下环境信息

**Comment by bitzyz** [comment]
如果可以的话，提供一下模型文件(yolov8n.onnx )

**Comment by GreatV** [comment]
@bitzyz 

- [yolov8n.onnx.zip](https://github.com/InfiniTensor/InfiniTensor/files/13630560/yolov8n.onnx.zip)

**Comment by bitzyz** [comment]
我这边用您的模型文件尝试着复现了一下，但是没有复现成功，您可以基于最新的master分支再测试一下，我这边是会报resize算子缺失问题，这个我们正在添加中，但没有出现您描述的卡住的问题，您可以再确认一下。
