### ISSUE TITLE
镜像里面执行examples/python/resnet_inference.py 失败 cpu_runtime()

### ISSUE THREAD

**Issue by Lebhoryi** [InfiniTensor/InfiniTensor#212]
现在好像不支持cpu_runtime的model.run()

main分支，

错误日志：
```shell
root@cfd226d97bc6:/home/lebhoryi/Project/open_source/InfiniTensor# python examples/python/resnet_inference.py 

import backend: <module 'backend' from '/home/lebhoryi/Project/open_source/InfiniTensor/pyinfinitensor/src/pyinfinitensor/backend.cpython-310-aarch64-linux-gnu.so'>
Stack trace (most recent call last):
#24   Object "/usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1", at 0xffffffffffffffff, in 
#23   Object "/usr/bin/python3.10", at 0xaaaacd62a62f, in _start
#22   Object "/usr/lib/aarch64-linux-gnu/libc.so.6", at 0xffff9a5674cb, in __libc_start_main
#21   Object "/usr/lib/aarch64-linux-gnu/libc.so.6", at 0xffff9a5673fb, in 
#20   Object "/usr/bin/python3.10", at 0xaaaacd62a747, in Py_BytesMain
#19   Object "/usr/bin/python3.10", at 0xaaaacd65bfbf, in Py_RunMain
#18   Object "/usr/bin/python3.10", at 0xaaaacd66b69f, in _PyRun_AnyFileObject
#17   Object "/usr/bin/python3.10", at 0xaaaacd66bad3, in _PyRun_SimpleFileObject
#16   Object "/usr/bin/python3.10", at 0xaaaacd66c96b, in 
#15   Object "/usr/bin/python3.10", at 0xaaaacd6653c7, in 
#14   Object "/usr/bin/python3.10", at 0xaaaacd66ccbb, in 
#13   Object "/usr/bin/python3.10", at 0xaaaacd6395e3, in PyEval_EvalCode
#12   Object "/usr/bin/python3.10", at 0xaaaacd63975f, in 
#11   Object "/usr/bin/python3.10", at 0xaaaacd53d3f7, in _PyEval_EvalFrameDefault
#10   Object "/usr/bin/python3.10", at 0xaaaacd555347, in _PyFunction_Vectorcall
#9    Object "/usr/bin/python3.10", at 0xaaaacd54177b, in _PyEval_EvalFrameDefault
#8    Object "/usr/bin/python3.10", at 0xaaaacd56443b, in 
#7    Object "/usr/bin/python3.10", at 0xaaaacd54ac9f, in _PyObject_MakeTpCall
#6    Object "/usr/bin/python3.10", at 0xaaaacd5546a3, in 
#5    Object "/home/lebhoryi/Project/open_source/InfiniTensor/pyinfinitensor/src/pyinfinitensor/backend.cpython-310-aarch64-linux-gnu.so", at 0xffff6553d1f3, in 
#4    Object "/home/lebhoryi/Project/open_source/InfiniTensor/pyinfinitensor/src/pyinfinitensor/backend.cpython-310-aarch64-linux-gnu.so", at 0xffff655649d3, in 
#3    Object "/home/lebhoryi/Project/open_source/InfiniTensor/pyinfinitensor/src/pyinfinitensor/backend.cpython-310-aarch64-linux-gnu.so", at 0xffff6552f86b, in 
#2    Source "/home/lebhoryi/Project/open_source/InfiniTensor/src/core/runtime.cc", line 21, in run
         19:     for (auto &op : graph->getOperators()) {
         20:         auto kernelAttrs = KernelAttrs{device, op->getOpType().underlying()};
      >  21:         Kernel *kernel = kernelRegistry.getKernel(kernelAttrs);
         22:         auto perfKey = PerfEngine::Key{kernelAttrs, op->getOpPerfKey()};
         23:         auto perfData = perfEngine.getPerfData(perfKey);
#1    Source "/home/lebhoryi/Project/open_source/InfiniTensor/include/core/kernel.h", line 105, in getKernel
        102:     }
        103:     Kernel *getKernel(const KernelAttrs &kernelAttrs) const {
        104:         auto it = kernels.find(kernelAttrs);
      > 105:         IT_ASSERT(it != kernels.end(), "Kernel not found for key {" +
        106:                                            get_kernel_attrs_str(kernelAttrs) +
        107:                                            "}");
        108:         return std::get<0>(it->second);
#0    Source "/home/lebhoryi/Project/open_source/InfiniTensor/src/utils/exception.cc", line 15, in Exception
         12: Exception::Exception(const std::string &msg)
         13:     : std::runtime_error(msg), info(msg) {
         14:     backward_trace::StackTrace st;
      >  15:     st.load_here(32);
         16:     backward_trace::Printer p;
         17:     p.print(st);
         18: }
Traceback (most recent call last):
  File "/home/lebhoryi/Project/open_source/InfiniTensor/examples/python/resnet_inference.py", line 19, in <module>
    model.run()
  File "/home/lebhoryi/Project/open_source/InfiniTensor/pyinfinitensor/src/pyinfinitensor/onnx.py", line 1366, in run
    self.handler.run()
RuntimeError: [/home/lebhoryi/Project/open_source/InfiniTensor/include/core/kernel.h:105] Assertion failed (it != kernels.end()): Kernel not found for key {CPU, Reshape}
```

**Comment by bitzyz** [comment]
可尝试使用cuda_runtime跑模型， cpu侧目前算子搭建不够完善，我们后续会逐步完善cpu侧算子。

**Comment by Lebhoryi** [comment]
@bitzyz 感谢回复。已经用cuda_runtime正常运行。
另外想问一下，论文中表3的conv5x5 --> conv5x5转成conv3x3的示例，如果我想复现这个过程需要执行test/nnet中的哪个测试，想要了解下输入和输出，以及推导过程

**Comment by zhengly123** [comment]
@Lebhoryi 你好，推导过程可直接参考`test_conv2conv.cc`的运行结果。在[log目录](https://github.com/zhengly123/OSDI23-EinNet-AE/tree/main/test/nnet/log/conv2conv)中提供了一种推导过程。使用编译产生的`nnet_reader`可以读取每一步的推导结果。
[测试](https://github.com/zhengly123/OSDI23-EinNet-AE/blob/main/test/nnet/test_op_conv5x5.cc)中提供了一个Conv5x5变换前后的运行代码。推导部分自动生成计算图的部分尚未适配目前的InfiniTensor架构。
